### ISSUE TITLE
[Question]: Is there a way to make NuGet packages through Visual Studio?

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-Toolkit-Suite-NET-Core#11]
Might be a daft question, but is there a way to make NuGet packages through Visual Studio, since NuGet Package Explorer does not support `netcoreapp31` yet?

**Comment by tbolon** [comment]
The `Pack` option on the project contextual menu does that.

Please also note that with the changes introduced on #10, you can now directly create packages from the command line.

**Comment by tbolon** [comment]
But note that the `Pack` option is not really reliable.

So the general recommendation is now to use `dotnet pack` (not applicable here) or `MSBuild` with the `Pack` target (what I do in `build.proj`)
