### ISSUE TITLE
Consider renaming the libraries to replace the whitespace char by a dot.

### ISSUE THREAD

**Issue by tbolon** [Wagnerp/Krypton-Toolkit-Suite-NET-Core#21]
Currently the libraries uses "Krypton Toolkit.dll", "Krypton Ribbon.dll", etc. as dll name.

I think it's pretty rare to have a space in the file name (in fact I have never seen any .NET assembly doing the same).

Also, my other suggestion will be to use the name of the assembly as the package name on nuget.org for better discoverability, and the package id can not contains a whitespace.

The general recommendation is to follow the root namespace, but I think we can't do this, as ComponentFactory is the name of the organization of Phil Wright on github: https://github.com/ComponentFactory. And naming the assembly "ComponentFactory.Krypton.Toolkit" could lead to confusion (and being in violation of Phil Wright  copyright).

My suggestion is to use the name "Krypton.Toolkit" for the toolkit, "Krypton.Ribbon" for the ribbon, and so on.

This will be a breaking change for people using the library file in scripts because the name will change.

But because we are creating a new package, I think it could be the right time to rename the files as the package reference will require to update the .NET project anyway.

If you are afraid of renaming the file, so my suggestion will be to at least rename the package to use more standard names (Krypton.Toolkit, Krypton.Ribbon, etc.).

If this suggestion is dropped, then I will create a new one regarding the package naming.

**Comment by Wagnerp** [comment]
The only concern I really have is breaking other developers projects (and the fallout from that) I think @Smurf-IV & I discussed renaming the namespace about a year ago, but it could be a idea for devs starting out on new projects.

I have renamed the assembly names though!
