### ISSUE TITLE
[Suggestion]: Putting a check in build.cmd to remind to change build/release #

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-Toolkit-Suite-NET-Core#22]
Put a check in build.cmd to remind to change build/release #. If `Y` is pressed, continue build/push, `N` is pressed abort process & point to file that needs to be changed.

Helps with house cleaning.

**Comment by tbolon** [comment]
Remember that nuget does not allow to overwrite a package with the same version number.

So if you forgot to change the version number between two publications, the operation will fail anyway.

**Comment by Wagnerp** [comment]
That's why I'm suggesting this, to prevent NuGet push failures. If you look at `build.cmd` I've started implementing a check, though I don't know if the syntax is right.

**Comment by Wagnerp** [comment]
Implemented!
