### ISSUE TITLE
[Other Issues]: Support for .NET 3.5

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-Toolkit-Suite-NET-Core#26]
Hi

Just giving everyone a heads up. A user on Discord has said that their company would like to migrate from a very old commercial version to the current version, but the only problem was that it was still using .NET 3.5.

For more info, see the Discord chat. TLDR they were experiencing debug issues moving to the `400` version, was there any plans on releasing a `350` repo?

I said no, but could modify the .NET Core configs to output 3.5 binaries. Was wondering if I do this, would I need to update the NuGet generation files?

**Comment by tbolon** [comment]
That should work. You could add net35 target and see if it compiles without modification.

Again, if some code must be changed to be compatible, you could use `#if NET35 ... #else ... #endif` to keep one single file for all .target frameworks.

**Comment by Wagnerp** [comment]
Hi @tbolon 

Thanks for the message. I've tried compiling the `2002` (aka February update) with net35 compatibility, but got some errors. Not sure if `AssemblyInfo` is still causing a issue.

"T:\Development\Krypton\Versions\Standard\Krypton-Toolkit-Suite-NET-Core\build.proj" (Pack target) (1) ->
"T:\Development\Krypton\Versions\Standard\Krypton-Toolkit-Suite-NET-Core\Source\Krypton Components\ComponentFactory.Kry
pton.Docking\Krypton.Docking 2019.csproj" (Pack target) (2:96) ->
"T:\Development\Krypton\Versions\Standard\Krypton-Toolkit-Suite-NET-Core\Source\Krypton Components\ComponentFactory.Kry
pton.Docking\Krypton.Docking 2019.csproj" (Build target) (2:97) ->
"T:\Development\Krypton\Versions\Standard\Krypton-Toolkit-Suite-NET-Core\Source\Krypton Components\ComponentFactory.Kry
pton.Navigator\Krypton.Navigator 2019.csproj" (default target) (3:147) ->
"T:\Development\Krypton\Versions\Standard\Krypton-Toolkit-Suite-NET-Core\Source\Krypton Components\ComponentFactory.Kry
pton.Toolkit\Krypton.Toolkit 2019.csproj" (default target) (4:198) ->
(CoreCompile target) ->
  Properties\AssemblyInfo.cs(26,12): error CS0246: The type or namespace name 'SecurityRulesAttribute' could not be fou
nd (are you missing a using directive or an assembly reference?) [T:\Development\Krypton\Versions\Standard\Krypton-Tool
kit-Suite-NET-Core\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\Krypton.Toolkit 2019.csproj]
  Properties\AssemblyInfo.cs(26,12): error CS0246: The type or namespace name 'SecurityRules' could not be found (are y
ou missing a using directive or an assembly reference?) [T:\Development\Krypton\Versions\Standard\Krypton-Toolkit-Suite
-NET-Core\Source\Krypton Components\ComponentFactory.Krypton.Toolkit\Krypton.Toolkit 2019.csproj]
  Properties\AssemblyInfo.cs(26,26): error CS0103: The name 'SecurityRuleSet' does not exist in the current context [T:
\Development\Krypton\Versions\Standard\Krypton-Toolkit-Suite-NET-Core\Source\Krypton Components\ComponentFactory.Krypto
n.Toolkit\Krypton.Toolkit 2019.csproj]

**Comment by tbolon** [comment]
Let me check

**Comment by tbolon** [comment]
I have updated the code to include compatible alternatives when code was not available in .net 3.5.

Essentially, it was `string.IsNullOrWhiteSpace()` and  `Enum.HasFlag`.
