### ISSUE TITLE
[BUG]: KryptonForm crashing Visual Studio

### ISSUE THREAD

**Issue by Wagnerp** [Wagnerp/Krypton-Toolkit-Suite-NET-Core#28]
Hi

Is anyone else experiencing crashes when attempting to switch to design mode when using `KryptonForm`?

**Comment by Tape-Worm** [comment]
Yep. I am. I updated to 5.500.2002 tonight and I have the same issue.

Not only that, but when I run my application, I get a stackoverflowexception on the constructor of my form:
![image](https://user-images.githubusercontent.com/9710137/73910656-340b1c80-486d-11ea-9afa-b35d257bf17c.png)

This never happened with Krypton v472.  Could these two issues be related?

**Comment by Tape-Worm** [comment]
I just attached another instance of VS to my instance with the krypton form in it and as soon as I opened the form in the IDE I got a stackoverflowexception.

![image](https://user-images.githubusercontent.com/9710137/73911530-6158ca00-486f-11ea-983f-972b96c2bfe8.png)

So it seems like it's all related.

**Comment by Tape-Worm** [comment]
OK, I figured it out.

In your constructor for KryptonForm you have this:
```csharp
if (!GetIsInAdministratorMode())
```
And the method has this:
```csharp
        /// <summary>Gets the is in administrator mode.</summary>
        /// <returns>IsInAdministratorMode</returns>
        public static bool GetIsInAdministratorMode()
        {
            KryptonForm form = new KryptonForm();

            return form.IsInAdministratorMode;
        }
```
As you can see, you're calling the `GetIsInAdministratorMode` in the ctor, and in the method, it's calling the ctor, which is calling `GetIsInAdministratorMode`, which is calling the ctor...

You get the idea.

**Comment by Wagnerp** [comment]
Weird, because that code didn't change between 5.4xx and 5.500... unless there are issues with `netcoreapp3.1`? Does this always return `true`?

**Comment by tbolon** [comment]
I think this code was added on 726603a7f8d09082386fd8e2ffaa69c0999e653a and 6083f783c31675000e858245a0e49ad624187c08 when trying to fix #17

**Comment by tbolon** [comment]
I don't understand what these changes were supposed to fix.

Creating a new KryptonForm inside a method (and never disposing it) will cause memory leaks. And setting an instance property value will never change anything.

I suggest we rollback these changes then review the original #17 issue and rewrite a new fix.

**Comment by tbolon** [comment]
I found the original commit which introduced this change: https://github.com/Wagnerp/Krypton-NET-5.470/commit/4121e8c4

I see several problems with this code.

IsInAdministratorMode should be static/get only (no reason it's different between two instances) if it's supposed to detect if the user is in admin mode.

I suppose this commit was added to append automatically a suffix to the window title when the user is an administrator.

If you want to allow the developer to hide this suffix, IsInAdministratorMode should be kept readonly and a new property (for example AppendAdministratorText) which could be defaulted to true or false (depending if you want to change the previous behavior by default) could be responsible to append the text or not.

For now, I will revert the changes which cause the SO exception, then we will discuss this changes in #17.

**Comment by Wagnerp** [comment]
Ahh got it... I think 

```cs
   if (!GetIsInAdministratorMode())
   {
        // Hide window
        Hide();
    }
    else
    {
        Show();
    }
```

Needs to alter the window text, **not** show/hide the window!

Schoolboy error!

**Comment by tbolon** [comment]
I'll let you handle that

**Comment by Wagnerp** [comment]
New code, though `{` may cause issues

```cs
   if (GetIsInAdministratorMode())
            {
                // Create a temporary variable to hold window text
                string tempText = Text;

                switch (BracketType)
                {
                    case BracketType.CURVEDBRACKET:
                        Text = $"({ tempText })";
                        break;
                    case BracketType.CURLYBRACKET:
                        Text = $"{{ tempText }}";
                        break;
                    case BracketType.SQUAREBRACKET:
                        Text = $"[{ tempText }]";
                        break;
                    case BracketType.NOBRACKET:
                        Text = $"{ tempText }";
                        break;
                    default:
                        break;
                }
            }
            else
            {
                Text = Text;
            }
```
And I'll take the previous comment by @tbolon into account

**Comment by Wagnerp** [comment]
Hold on...

I forgot that I wrote this ages ago!!!

```cs
    /// <summary>
        /// Updates the title.
        /// </summary>
        /// <param name="hasAdministrativeRights">if set to <c>true</c> [has administrative rights].</param>
        /// <param name="bracketType">The type of bracket that will encapsulate the administrator text.</param>
        public void UpdateTitle(bool hasAdministrativeRights, BracketType bracketType = BracketType.CURVEDBRACKET)
        {
            if (hasAdministrativeRights)
            {
                switch (bracketType)
                {
                    case BracketType.CURVEDBRACKET:
                        Text = $@"{ Text } - ({ AdministratorText })";
                        break;
                    case BracketType.CURLYBRACKET:
                        Text = $@"{ Text } - {{{ AdministratorText}}}";
                        break;
                    case BracketType.SQUAREBRACKET:
                        Text = $@"{ Text } - [{ AdministratorText }]";
                        break;
                    case BracketType.NOBRACKET:
                        Text = $@"{ Text } - { AdministratorText }";
                        break;
                    default:
                        break;
                }
            }
        }
```

**Comment by Wagnerp** [comment]
This should simplify it `UpdateTitle(AppendAdministratorText, BracketType);`!!!

**Comment by Wagnerp** [comment]
@tbolon & @Smurf-IV  I think that I've misunderstood #17, which needs more discussion. A discussion needs to be held in regards to what happens **if** elevation is required, but we're still running as a normal user?

**Comment by Tape-Worm** [comment]
You guys have any ETA on when the nuget packages will be updated?

**Comment by Smurf-IV** [comment]
> 
> 
> @tbolon & @Smurf-IV I think that I've misunderstood #17, which needs more discussion. A discussion needs to be held in regards to what happens **if** elevation is required, but we're still running as a normal user?

If the App requires elevation, then let the app sort it out; as in #17, It was displaying a message box asking the user to run in elavated mode.

**Comment by Wagnerp** [comment]
@Smurf-IV Yes I took the if statement out & reverted the code to before that change, but it still requires testing. Plus I'm leaving the developer decide on what to do, as per @tbolon comment about this.

@Tape-Worm I can't give you an ETA yet, as I need to fix my build environment, plus need to test the fixes.

**Comment by Wagnerp** [comment]
I don't think its the administrator code causing the issue, I have a feeling it's something else or .NET 3.5.
